ISLANDORA-2004: Makes use of new display aiding predicates
Islandora/islandora_internet_archive_bookreader pull request #108
Opened 2017-07-13 15:10 UTC by DiegoPino

JIRA Ticket: https://jira.duraspace.org/projects/ISLANDORA/issues/ISLANDORA-2004
Requires https://github.com/Islandora/islandora_paged_content/pull/132

# What does this Pull Request do?

Makes use of the 2 new predicates defined by https://github.com/Islandora/islandora_paged_content/pull/132

# What's new?
A simple change in the JS logic allowing for cover less books and per Object sequence display settings, making it possible to have 1-up and 2-up at the same time in a single repository.
Does not, I repeat, does not conflict with existing code, the way objects are displayed if not using the predicates and does not affect the main IA Book reader source code compatibility.

# How should this be tested?
 See https://github.com/Islandora/islandora_paged_content/pull/132

# Interested parties
Book addicts, @Islandora/7-x-1-x-committers, @adam-vessey @jordandukart @rosiel @qadan

2018-03-21 18:15 UTC, bondjimbond requested changes
@DiegoPino This is quite a bit behind now. On my vagrant machine I merged with the 7.x branch, and it works as advertised. If you resolve the conflicts this should be approvable.

2018-03-21 19:34 UTC, DiegoPino commented
@bondjimbond cool. Will rebase and let's see how that goes.

2018-03-21 20:22 UTC, DiegoPino commented
@bondjimbond don't react yet 😿 . I hate rebasing and this one went surreal. Let me fix this stuff... will force push on a clean stuff.

2018-03-21 20:35 UTC, DiegoPino commented
@bondjimbond hu! git nightmare. Ok, fixed the mess. This should go clean on top of 7.x now. Maybe some DCS issue inbetween because my local libraries are newer, but hopping not. Sadly i had to reset hard, rebase and hard push the branch back. Let me know if this looks good, i would ask you, if possible to retests since i don't know how this plays with some new code. Thanks!

2018-03-22 13:10 UTC, bondjimbond approved these changes

2018-03-22 13:10 UTC, bondjimbond commented
Still seems to work. Thanks for this! It came at exactly the time when I needed it.

2018-03-26 18:09 UTC, bondjimbond commented
Aaand I don't know why I lost all my merging tasks last week. This is good to go.

2018-03-26 18:09 UTC, merged